# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 138c27c45b456972a63dbe2aca37d842a6553023af606ddd8357c19d0c28fc54e2eed572881b2fd9a959c3d89af66a53d87fe4ff95e229da3ebc9c4928c7e0bc

test:
  secret_key_base: 6e833a11e95efc736c6dce41bb480c79026afa22e56050f16f39a0c5587b7fd7b7bab18c9b089d98a3933add4a94885b03a42930ab1927e855890b1c821eebcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
